/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CompetitionService } from "../competition.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CompetitionCreateInput } from "./CompetitionCreateInput";
import { CompetitionWhereInput } from "./CompetitionWhereInput";
import { CompetitionWhereUniqueInput } from "./CompetitionWhereUniqueInput";
import { CompetitionFindManyArgs } from "./CompetitionFindManyArgs";
import { CompetitionUpdateInput } from "./CompetitionUpdateInput";
import { Competition } from "./Competition";
import { AthleteFindManyArgs } from "../../athlete/base/AthleteFindManyArgs";
import { Athlete } from "../../athlete/base/Athlete";
import { AthleteWhereUniqueInput } from "../../athlete/base/AthleteWhereUniqueInput";
import { SponsorFindManyArgs } from "../../sponsor/base/SponsorFindManyArgs";
import { Sponsor } from "../../sponsor/base/Sponsor";
import { SponsorWhereUniqueInput } from "../../sponsor/base/SponsorWhereUniqueInput";
import { TeamFindManyArgs } from "../../team/base/TeamFindManyArgs";
import { Team } from "../../team/base/Team";
import { TeamWhereUniqueInput } from "../../team/base/TeamWhereUniqueInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CompetitionControllerBase {
  constructor(
    protected readonly service: CompetitionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Competition })
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: CompetitionCreateInput
  ): Promise<Competition> {
    return await this.service.create({
      data: {
        ...data,

        accounts: {
          connect: data.accounts,
        },
      },
      select: {
        accounts: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Competition] })
  @ApiNestedQuery(CompetitionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Competition[]> {
    const args = plainToClass(CompetitionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        accounts: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Competition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: CompetitionWhereUniqueInput
  ): Promise<Competition | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        accounts: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Competition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() data: CompetitionUpdateInput
  ): Promise<Competition | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          accounts: {
            connect: data.accounts,
          },
        },
        select: {
          accounts: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Competition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: CompetitionWhereUniqueInput
  ): Promise<Competition | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          accounts: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/athlete")
  @ApiNestedQuery(AthleteFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Athlete",
    action: "read",
    possession: "any",
  })
  async findManyAthlete(
    @common.Req() request: Request,
    @common.Param() params: CompetitionWhereUniqueInput
  ): Promise<Athlete[]> {
    const query = plainToClass(AthleteFindManyArgs, request.query);
    const results = await this.service.findAthlete(params.id, {
      ...query,
      select: {
        accounts: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        starts: true,
        updatedAt: true,
        votes: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/athlete")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async connectAthlete(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: AthleteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      athlete: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/athlete")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async updateAthlete(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: AthleteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      athlete: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/athlete")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async disconnectAthlete(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: AthleteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      athlete: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/sponsors")
  @ApiNestedQuery(SponsorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sponsor",
    action: "read",
    possession: "any",
  })
  async findManySponsors(
    @common.Req() request: Request,
    @common.Param() params: CompetitionWhereUniqueInput
  ): Promise<Sponsor[]> {
    const query = plainToClass(SponsorFindManyArgs, request.query);
    const results = await this.service.findSponsors(params.id, {
      ...query,
      select: {
        athlete: {
          select: {
            id: true,
          },
        },

        competition: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sponsors")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async connectSponsors(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: SponsorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sponsors: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sponsors")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async updateSponsors(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: SponsorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sponsors: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sponsors")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async disconnectSponsors(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: SponsorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sponsors: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/team")
  @ApiNestedQuery(TeamFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Team",
    action: "read",
    possession: "any",
  })
  async findManyTeam(
    @common.Req() request: Request,
    @common.Param() params: CompetitionWhereUniqueInput
  ): Promise<Team[]> {
    const query = plainToClass(TeamFindManyArgs, request.query);
    const results = await this.service.findTeam(params.id, {
      ...query,
      select: {
        accounts: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/team")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async connectTeam(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: TeamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      team: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/team")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async updateTeam(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: TeamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      team: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/team")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async disconnectTeam(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: TeamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      team: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/user")
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async findManyUser(
    @common.Req() request: Request,
    @common.Param() params: CompetitionWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUser(params.id, {
      ...query,
      select: {
        athlete: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        starts: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
        vote: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/user")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async connectUser(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      user: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/user")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async updateUser(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      user: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/user")
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "update",
    possession: "any",
  })
  async disconnectUser(
    @common.Param() params: CompetitionWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      user: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
