/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AthleteCreateNestedManyWithoutTeamsInput } from "./AthleteCreateNestedManyWithoutTeamsInput";
import { CompetitionCreateNestedManyWithoutTeamsInput } from "./CompetitionCreateNestedManyWithoutTeamsInput";
import { SponsorCreateNestedManyWithoutTeamsInput } from "./SponsorCreateNestedManyWithoutTeamsInput";
import { UserCreateNestedManyWithoutTeamsInput } from "./UserCreateNestedManyWithoutTeamsInput";

@InputType()
class TeamCreateInput {
  @ApiProperty({
    required: true,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @Field(() => AccountWhereUniqueInput)
  accounts!: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AthleteCreateNestedManyWithoutTeamsInput,
  })
  @ValidateNested()
  @Type(() => AthleteCreateNestedManyWithoutTeamsInput)
  @IsOptional()
  @Field(() => AthleteCreateNestedManyWithoutTeamsInput, {
    nullable: true,
  })
  athlete?: AthleteCreateNestedManyWithoutTeamsInput;

  @ApiProperty({
    required: false,
    type: () => CompetitionCreateNestedManyWithoutTeamsInput,
  })
  @ValidateNested()
  @Type(() => CompetitionCreateNestedManyWithoutTeamsInput)
  @IsOptional()
  @Field(() => CompetitionCreateNestedManyWithoutTeamsInput, {
    nullable: true,
  })
  competitions?: CompetitionCreateNestedManyWithoutTeamsInput;

  @ApiProperty({
    required: false,
    type: () => SponsorCreateNestedManyWithoutTeamsInput,
  })
  @ValidateNested()
  @Type(() => SponsorCreateNestedManyWithoutTeamsInput)
  @IsOptional()
  @Field(() => SponsorCreateNestedManyWithoutTeamsInput, {
    nullable: true,
  })
  sponsors?: SponsorCreateNestedManyWithoutTeamsInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutTeamsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutTeamsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutTeamsInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutTeamsInput;
}

export { TeamCreateInput as TeamCreateInput };
