/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CompetitionUpdateManyWithoutAthletesInput } from "./CompetitionUpdateManyWithoutAthletesInput";
import { SponsorUpdateManyWithoutAthletesInput } from "./SponsorUpdateManyWithoutAthletesInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TeamUpdateManyWithoutAthletesInput } from "./TeamUpdateManyWithoutAthletesInput";
import { UserUpdateManyWithoutAthletesInput } from "./UserUpdateManyWithoutAthletesInput";

@InputType()
class AthleteUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  accounts?: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CompetitionUpdateManyWithoutAthletesInput,
  })
  @ValidateNested()
  @Type(() => CompetitionUpdateManyWithoutAthletesInput)
  @IsOptional()
  @Field(() => CompetitionUpdateManyWithoutAthletesInput, {
    nullable: true,
  })
  competitions?: CompetitionUpdateManyWithoutAthletesInput;

  @ApiProperty({
    required: false,
    type: () => SponsorUpdateManyWithoutAthletesInput,
  })
  @ValidateNested()
  @Type(() => SponsorUpdateManyWithoutAthletesInput)
  @IsOptional()
  @Field(() => SponsorUpdateManyWithoutAthletesInput, {
    nullable: true,
  })
  sponsors?: SponsorUpdateManyWithoutAthletesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  starts?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TeamUpdateManyWithoutAthletesInput,
  })
  @ValidateNested()
  @Type(() => TeamUpdateManyWithoutAthletesInput)
  @IsOptional()
  @Field(() => TeamUpdateManyWithoutAthletesInput, {
    nullable: true,
  })
  teams?: TeamUpdateManyWithoutAthletesInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutAthletesInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutAthletesInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutAthletesInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutAthletesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  votes?: InputJsonValue;
}

export { AthleteUpdateInput as AthleteUpdateInput };
