/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CompetitionListRelationFilter } from "../../competition/base/CompetitionListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { SponsorListRelationFilter } from "../../sponsor/base/SponsorListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { TeamListRelationFilter } from "../../team/base/TeamListRelationFilter";
import { UserListRelationFilter } from "../../user/base/UserListRelationFilter";

@InputType()
class AthleteWhereInput {
  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  accounts?: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CompetitionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CompetitionListRelationFilter)
  @IsOptional()
  @Field(() => CompetitionListRelationFilter, {
    nullable: true,
  })
  competitions?: CompetitionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => SponsorListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SponsorListRelationFilter)
  @IsOptional()
  @Field(() => SponsorListRelationFilter, {
    nullable: true,
  })
  sponsors?: SponsorListRelationFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  starts?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => TeamListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TeamListRelationFilter)
  @IsOptional()
  @Field(() => TeamListRelationFilter, {
    nullable: true,
  })
  teams?: TeamListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserListRelationFilter)
  @IsOptional()
  @Field(() => UserListRelationFilter, {
    nullable: true,
  })
  users?: UserListRelationFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  votes?: JsonFilter;
}

export { AthleteWhereInput as AthleteWhereInput };
