/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Player,
  Competition,
  Sponsor,
  Team,
  User,
  Account,
} from "@prisma/client";

export class PlayerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.PlayerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PlayerFindManyArgs>
  ): Promise<number> {
    return this.prisma.player.count(args);
  }

  async findMany<T extends Prisma.PlayerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PlayerFindManyArgs>
  ): Promise<Player[]> {
    return this.prisma.player.findMany(args);
  }
  async findOne<T extends Prisma.PlayerFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PlayerFindUniqueArgs>
  ): Promise<Player | null> {
    return this.prisma.player.findUnique(args);
  }
  async create<T extends Prisma.PlayerCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PlayerCreateArgs>
  ): Promise<Player> {
    return this.prisma.player.create<T>(args);
  }
  async update<T extends Prisma.PlayerUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PlayerUpdateArgs>
  ): Promise<Player> {
    return this.prisma.player.update<T>(args);
  }
  async delete<T extends Prisma.PlayerDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PlayerDeleteArgs>
  ): Promise<Player> {
    return this.prisma.player.delete(args);
  }

  async findCompetitions(
    parentId: string,
    args: Prisma.CompetitionFindManyArgs
  ): Promise<Competition[]> {
    return this.prisma.player
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .competitions(args);
  }

  async findSponsors(
    parentId: string,
    args: Prisma.SponsorFindManyArgs
  ): Promise<Sponsor[]> {
    return this.prisma.player
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .sponsors(args);
  }

  async findTeams(
    parentId: string,
    args: Prisma.TeamFindManyArgs
  ): Promise<Team[]> {
    return this.prisma.player
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .teams(args);
  }

  async findUsers(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.player
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .users(args);
  }

  async getAccounts(parentId: string): Promise<Account | null> {
    return this.prisma.player
      .findUnique({
        where: { id: parentId },
      })
      .accounts();
  }
}
