/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CompetitionUpdateManyWithoutPlayersInput } from "./CompetitionUpdateManyWithoutPlayersInput";
import { SponsorUpdateManyWithoutPlayersInput } from "./SponsorUpdateManyWithoutPlayersInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TeamUpdateManyWithoutPlayersInput } from "./TeamUpdateManyWithoutPlayersInput";
import { UserUpdateManyWithoutPlayersInput } from "./UserUpdateManyWithoutPlayersInput";

@InputType()
class PlayerUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  accounts?: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CompetitionUpdateManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => CompetitionUpdateManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => CompetitionUpdateManyWithoutPlayersInput, {
    nullable: true,
  })
  competitions?: CompetitionUpdateManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
    type: () => SponsorUpdateManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => SponsorUpdateManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => SponsorUpdateManyWithoutPlayersInput, {
    nullable: true,
  })
  sponsors?: SponsorUpdateManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  starts?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TeamUpdateManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => TeamUpdateManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => TeamUpdateManyWithoutPlayersInput, {
    nullable: true,
  })
  teams?: TeamUpdateManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutPlayersInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  votes?: InputJsonValue;
}

export { PlayerUpdateInput as PlayerUpdateInput };
